language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.19
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8.3

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.19

install:
  - pip install -q Django==$DJANGO_VERSION
  - "make install"

script: coverage run --source=django_thumbor manage.py test

after_success:
    coveralls
